-- AlterTable
ALTER TABLE "public"."workspaces" ADD COLUMN     "kpiCompletionWeight" DOUBLE PRECISION NOT NULL DEFAULT 30.0,
ADD COLUMN     "kpiFollowerWeight" DOUBLE PRECISION NOT NULL DEFAULT 15.0,
ADD COLUMN     "kpiProductivityWeight" DOUBLE PRECISION NOT NULL DEFAULT 20.0,
ADD COLUMN     "kpiReviewWeight" DOUBLE PRECISION NOT NULL DEFAULT 15.0,
ADD COLUMN     "kpiSlaWeight" DOUBLE PRECISION NOT NULL DEFAULT 20.0;
