export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACES_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID!;
export const IMAGES_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!;
export const MEMBERS_ID = process.env.NEXT_PUBLIC_APPWRITE_MEMBERS_ID!;
export const TASKS_ID = process.env.NEXT_PUBLIC_APPWRITE_TASKS_ID!;
export const SERVICES_ID = process.env.NEXT_PUBLIC_APPWRITE_SERVICES_ID!;
export const TASK_HISTORY_ID = process.env.NEXT_PUBLIC_APPWRITE_TASK_HISTORY_ID!;
export const TASK_MESSAGES_ID = process.env.NEXT_PUBLIC_APPWRITE_TASK_MESSAGES_COLLECTION_ID!;


